config/routes.rb
ProjectTeacher::Application.routes.draw do

  resources :invitations

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  
  get 'sign_up/:invitation_token' , :controller => 'users', :action => 'new'
  get 'sign_up' => 'users#new', as: 'sign_up'
  
  get 'comments/update_courses/:id' => 'comments#update_courses'

  resources :schools

  resources :comments

  resources :teachers

  resources :courses

  resources :majors

  resources :users

  resources :rols

  resources :sessions

  root 'home#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :teacher
  belongs_to :course
  belongs_to :user

  validates :teacher_id, format: { with: /\A\d+\z/, message:'Maestro no valido'}
  validates :course_id, format: { with: /\A\d+\z/, message: 'Materia no valido'}
  validates :user_id, format: { with: /\A\d+\z/, message:'Nombre no valido'}
  validates :date_post, presence: { message: 'La fecha no puede estar en blanco' }
  validates :content, format: { with: /\A[a-z|A-Z|0-;|,|.|ñ| |á|é|í|ó|ú|ü]{,255}\z/, message:'Comentario no valido' }

  def contenido
  	largo = self.content.length
	i = 0
	j = 100
	cad = ''
	while i <= largo 
		cad += "#{self.content[i..j]}\n"
		i = j+1
		j = i+100
	end 
	cad
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :update_courses]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comentario creado correctamente.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /comments/update_courses/1
  def update_courses
    teacher=Teacher.find(params[:id]) unless params[:id].blank?
    courses=nil
    if(teacher==nil)
      courses=current_user.materias
    else
      courses=teacher.courses
    end
   
     render :partial => "courses", :locals => { :courses => courses }
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comentario actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.delete
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:teacher_id, :course_id, :user_id, :date_post, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_courses.html.erb
<%= form_for(@comment, :remote=>true) do |f| %>

    <% if !courses.blank? %>
      <%= f.collection_select :course_id , courses , :id, :name, { prompt: true }, { class: 'form-control' }%>
    <% else %>
      <%= f.collection_select :course_id, [] , :id, :name, { prompt: true }, { class: 'form-control' }%>
    <% end %>

   <%= f.hidden_field :user_id, :value => "#{current_user.id}" %>
  <%= f.hidden_field :date_post, :value => "#{Date.today}" %>
  <div class='field'>
    <%= f.label :content, 'Comentario' %>
    <%= f.text_area :content, class:'form-control', maxlength: '254', style: 'resize:none; width:450px; height:80px;' %>
  </div>
  <br>
  <button type='submit' class='btn btn-primary btn-sm' onclick="window.location.href='<%= comments_path %>'"> Guardar </button>
    
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment, :remote=>true) do |f| %>

  <%= render 'layouts/error_messages', object: @comment %>

  <div class='field'>
    <%= f.label :teacher_id, 'Profesor' %>
    <%= f.collection_select :teacher_id, current_user.profesores, :id, :full_name, { prompt: true }, { class: 'form-control', id: 'comment_teacher_id' } %>    
  </div>
  <div id="courses",class='field'>
    <%= f.label :course_id, 'Materia' %>
    <%= render :partial => 'courses', :locals => { :courses => current_user.materias }  %>
  </div>
  
<% end %>

app/views/comments/edit.html.erb
<h1>Editar comentario</h1>
<div class='col-md-4'>
	<%= render 'form' %>
	<br>
	<%= link_to 'Volver', comments_path %>
</div>

app/views/comments/index.html.erb
<h1>Comentarios</h1>
<% if @comments.nil? || @comments.count <= 0 %>
  <p class='text-danger'> No hay comentarios.</p>
<% else %>
	<table class='table table-striped table-bordered table-hover'>
  <thead>
    <tr>
      <th width='20%'>Profesor</th>
      <th width='20%'>Comentario</th>
      <th width='20%'>Materia</th>
      <th width='12%'>Fecha</th>
      <% if current_user.admin %>
        <th width='4%'></th>
      <% end %>
      <th width='4%'></th>
    </tr>
  </thead>
  <tbody>
	<% current_user.comentarios.each do |comment| %>
  <tr>
    <td> <%= link_to comment.teacher.full_name, teacher_path(comment.teacher.id) %></td>
    <td> <%= link_to "#{comment.content[0..20]}", comment_path(comment) %> </td>
    <td> <%= link_to comment.course.name, course_path(comment.course.id) %></td>
    <td> <%= comment.date_post %></td>
    <% if current_user.admin? %>
    	<td><%= link_to 'Editar', edit_comment_path(comment) %></td>
    <% end %>
    <td><%= link_to 'Eliminar', comment, method: :delete, data: { confirm: '¿Seguro?' } %></td>
  </tr>
  <% end %>
  </tbody>
	</table>
<% end %>
<br>
<button class='btn btn-primary btn-sm' type='button' onclick="window.location.href='<%= new_comment_path %>'" > Nuevo </button>

app/views/comments/new.html.erb
<h1>Nuevo comentario</h1>
<div class='col-md-4'>
	<%= render 'form' %>
	<br>
	<%= link_to 'Volver', comments_path %>
</div>

app/views/comments/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-dismissable alert-success">
    <%= notice %>
  </div>
<% end %>

<div>
  <b>Fecha:</b>
  <%= @comment.date_post %>
</div>

<div>
  <strong>Profesor:</strong>
  <%= @comment.teacher.full_name %>
</div>

<div>
  <strong>Materia:</strong>
  <%= @comment.course.name %>
</div>

<div>
  <strong>Comentario:</strong><br>
  <%= @comment.contenido %>
</div>
<br>
<%= link_to 'Editar', edit_comment_path(@comment) %> |
<%= link_to 'Volver', comments_path %>