config/routes.rb
ProjectTeacher::Application.routes.draw do

  resources :invitations

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  
  get 'sign_up/:invitation_token' , :controller => 'users', :action => 'new'
  get 'sign_up' => 'users#new', as: 'sign_up'
  
  get 'comments/update_courses/:id' => 'comments#update_courses'

  resources :schools

  resources :comments

  resources :teachers

  resources :courses

  resources :majors

  resources :users

  resources :rols

  resources :sessions

  root 'home#index'

  

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base

  has_many :comments
  has_and_belongs_to_many :courses
  
  validates :name, length: { in: 5..25, message: 'Longitud del nombre incorrecto' }, format: { with: /\A[a-zA-Z|á|é|í|ó|ú|ü| |ñ]+\z/, message:'Nombre no valido'}
  validates :last_name, length: { in: 4..25, message: 'Longitud del apellido paterno incorrecto' }, format: { with: /\A[a-zA-Z|á|é|í|ó|ú|ü| |ñ]+\z/, message:'Apellido paterno no valido'}
  validates :second_last_name, length: { in: 4..25, message: 'Longitud del apellido materno incorrecto' }, format: { with: /\A[a-zA-Z|á|é|í|ó|ú|ü| |ñ]*\z/, message:'Apellido materno no valido'}, if: :seco_last_name?

  has_attached_file :picture, :styles => { :mini => '128x128>', :thumb => '100x100>', :big => '500x500>' }

  def full_name
  	"#{name + ' ' + last_name + ' ' + second_last_name}"
  end

  def seco_last_name?
  	self.second_last_name.length > 0
  end  

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.update_attributes(teacher_params)
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Maestro creado correctamente.' }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    params[:teacher][:course_ids] ||= []
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Maestro actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.delete
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :last_name, :second_last_name, :picture, 
        {:course_ids => []}, :courses)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_admin.html.erb
<% if @teachers.count <= 0 %> 
  <p class='text-danger'>No hay profesores disponibles.</p><br>
<% else %>
<table class='table table-striped table-bordered table-hover'>
<thead>
  <tr>
    <th width='74%'> Nombre </th>
    <th width='8%'></th>
    <th width='8%'></th>
  </tr>
</thead>
<tbody>
  <% current_user.profesores.each do |teacher| %>
    <tr>
      <td><%= link_to "#{teacher.full_name}", teacher_path(teacher.id) %></td>
      <td><%= link_to 'Editar', edit_teacher_path(teacher) %></td>
      <td><%= link_to 'Eliminar', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>
<% end %>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>

  <%= render 'layouts/error_messages', object: @teacher %>

  <div class='field'>
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class='field'>
    <%= f.label :last_name, 'Apellido paterno' %>
    <%= f.text_field :last_name, class:'form-control' %>
  </div>
  <div class='field'>
    <%= f.label :second_last_name, 'Apellido materno' %>
    <%= f.text_field :second_last_name, class:'form-control' %>
  </div>
  <div class='field'>
    <%= f.label 'Materias' %>
    <% current_user.materias.each do |course| %>
        <br><%= check_box_tag 'teacher[course_ids][]', course.id, @teacher.courses.include?(course) %>
        <%= course.name %> 
    <% end %>
  </div>
  <div class='field'>
    <%= f.label :picture, 'Imagen' %>
    <%= f.file_field :picture %>
  </div>
  <br>
  <button type='submit' class='btn btn-primary btn-sm'> Guardar </button>
<% end %>

app/views/teachers/_user.html.erb
<% if @teachers.count <= 0 %> 
  <p class='text-danger'>No hay profesores disponibles.</p><br>
<% else %>
<table class='table table-striped table-bordered table-hover'>
<thead>
  <tr>
    <th width='74%'> Nombre </th>
    
  </tr>
</thead>
<tbody>
  <% current_user.profesores.each do |teacher| %>
    <tr>
      <td><%= link_to "#{teacher.full_name}", teacher_path(teacher.id) %></td>
     
    </tr>
  <% end %>
</tbody>
</table>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editar profesor</h1>
<div class='col-md-5'>
	<%= render 'form' %>
	<br>
	<%= link_to 'Volver', teachers_path %>
</div>

app/views/teachers/index.html.erb
<h1>Profesores</h1> 
<% if @teachers.count <= 0 %> 
  <p class='text-danger'>No hay profesores disponibles.</p><br>
<% else %>
<% if current_user.admin %>
    <%= render 'admin', object: @teachers %>
    <br>
    <button class='btn btn-primary btn-sm' type='button' onclick="window.location.href='<%= new_teacher_path %>'" > Nuevo </button>
  <% else %>
    <%= render 'user' %>
  <% end %>
<% end %>

app/views/teachers/new.html.erb
<h1>Nuevo profesor</h1>
<div class='col-md-5'>
	<%= render 'form' %>
	<br>
	<%= link_to 'Volver', teachers_path %>
</div>

app/views/teachers/show.html.erb
<% if flash[:notice] %>
	<div class="alert alert-dismissable alert-success">
		<%= notice %>
	</div>
<% end %>

<div class='col-md-3'>
	<% unless @teacher.picture_file_name.nil? %>
		<%= link_to @teacher.picture.url do %>
			<%= image_tag @teacher.picture.url(:mini) %>
		<% end %>
	<% end %>
	<br>
	<br>
	<% if current_user.admin %>
		<%= link_to 'Editar', edit_teacher_path(@teacher) %> |
	<% end %>
	<%= link_to 'Volver', teachers_path %>
</div>
<div class='col-md-9'>
	<h1> <%= @teacher.full_name %> </h1>
	<% if @teacher.courses.length <= 0 %>
			<p class='text-danger'> No hay materias asignadas </p>
	<% else %>
		<strong> Materias que imparte: </strong>
		<ul>
			<% @teacher.courses.each do |course| %>
				<li> <%= course.name %> </li>
			<% end %>
		</ul>
		<p align='middle'>
		<button class='btn btn-primary btn-sm' type='button' onclick="window.location.href='<%= new_comment_path %>'" > Comentar </button>
		</p>
		<% Teacher.find(params[:id]).comments.order('id').each do |comment| %>
			<br>
			<i> <strong> <%= comment.user.nickname %></strong></i>: 
			<ul> <%= comment.contenido %> </ul>
		<% end %>
	<% end %>
</div>