config/routes.rb
ProjectTeacher::Application.routes.draw do

  resources :invitations

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  
  get 'sign_up/:invitation_token' , :controller => 'users', :action => 'new'
  get 'sign_up' => 'users#new', as: 'sign_up'
  
  get 'comments/update_courses/:id' => 'comments#update_courses'

  resources :schools

  resources :comments

  resources :teachers

  resources :courses

  resources :majors

  resources :users

  resources :rols

  resources :sessions

  root 'home#index'

  

end

app/models/school.rb
class School < ActiveRecord::Base
  
  has_many :users
  has_many :majors  

  validates :name, format: { with: /\A[a-zA-Z|á|é|í|ó|ú|ü| |ñ]+\z/, message:'Nombre no valido'}

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'Escuela creada correctamente.' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'Escuela actualizada correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f|%>
  
  <%= render 'layouts/error_messages', object: @school %>

  <div class='field'>
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <br>
  <button type='submit' class='btn btn-primary btn-sm'> Guardar </button>
<% end %>

app/views/schools/edit.html.erb
<h1>Editar escuela</h1>
<div class='col-lg-4'>
	<%= render 'form' %>
	<br>
	<%= link_to 'Volver', schools_path %>
</div>

app/views/schools/index.html.erb
<h1>Escuelas</h1>
<% if @schools.count <= 0 %>
  <p class='text-danger'>No hay escuelas disponibles.</p><br>
<% else %>
<table  class='table table-striped table-bordered table-hover'>
  <thead>
    <tr>
      <th width='84%'>Nombre</th>
      <th width='8%'></th>
      <th width='8%'></th>
    </tr>
  </thead>
  <tbody>
    <% @schools.order('name').each do |school| %>
      <tr>
        <td><%= link_to "#{school.name}", school_path(school) %></td>
        <td><%= link_to 'Editar', edit_school_path(school) %></td>
        <td><%= link_to 'Eliminar', school, method: :delete, data: { confirm: '¿Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<button class='btn btn-primary btn-sm' type='button' onclick="window.location.href='<%= new_school_path %>'" > Nuevo </button>

app/views/schools/new.html.erb
<h1>Nueva escuela</h1>
<div class='col-lg-4'>
	<%= render 'form' %>
	<br>
	<%= link_to 'Volver', schools_path %>
</div>

app/views/schools/show.html.erb
<% if flash[:notice] %>
	<div class="alert alert-dismissable alert-success">
		<%= notice %>
	</div>
<% end %>

<h1> <%= @school.name %> </h1>
<br>
<b>Carreras impartidas:</b>
<ul>
	<il>
	<% Major.scoped_by_school_id(@school.id).each do |major| %>
		<%= link_to "#{major.name}", major_path(major) %><br>
	<% end %>
	</il>
</ul>
<br>
<%= link_to 'Editar', edit_school_path(@school) %> |
<%= link_to 'Volver', schools_path %>