config/routes.rb
ProjectTeacher::Application.routes.draw do

  resources :invitations

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  
  get 'sign_up/:invitation_token' , :controller => 'users', :action => 'new'
  get 'sign_up' => 'users#new', as: 'sign_up'
  
  get 'comments/update_courses/:id' => 'comments#update_courses'

  resources :schools

  resources :comments

  resources :teachers

  resources :courses

  resources :majors

  resources :users

  resources :rols

  resources :sessions

  root 'home#index'

  

end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
	<div class='alert alert-error' >
		<h2><%= pluralize(object.errors.count, "error") %>:</h2>
		<ul>
		<% object.errors.each do |att, error| %>
			<li><%= error %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class='container'>
	<a class='navbar-brand' href='../'> <%= image_tag '/pira01.png', size: '30x25', class:'vol_horizontal'%> Post-T </a>
	<div class='nav nav-collapse'>
    <ul class='nav navbar-nav navbar-right'>
    <% if current_user %>
    	<li class= 'dropdown'> 
    	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
				<span class='text-success'> <%= current_user.nickname %> </span>
			<b class="caret"></b> 
			</a>
			<ul class="dropdown-menu">
      	<li> <%= link_to 'Mi perfil', "#{user_path(current_user)}" %> </li>
      	<li> <%= link_to 'Salir', "#{log_out_path}" %> </li>
	   	</ul>
    	</li>
		<% end %>
   	</ul>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class='btn-group-vertical nav-collapse'>
		<button class='btn btn-default' type='button' onclick="window.location.href='<%= teachers_path %>'" > Profesores </button>
		<button class='btn btn-default' type='button' onclick="window.location.href='<%= comments_path %>'" > Comentarios </button>
  <% if current_user.admin %>
		<button class='btn btn-default' type='button' onclick="window.location.href='<%= schools_path %>'" > Escuelas </button>
		<button class='btn btn-default' type='button' onclick="window.location.href='<%= courses_path %>'" > Materias </button>
		<button class='btn btn-default' type='button' onclick="window.location.href='<%= majors_path %>'" > Carreras </button>
		<button class='btn btn-default' type='button' onclick="window.location.href='<%= users_path %>'" > Gente </button>
		<button class='btn btn-default' type='button' onclick="window.location.href='<%= rols_path %>'" > Roles </button>
	<%end %>
</div>

app/views/layouts/_without_log_in.html.erb
<div class='col-md-6'>
	<h1>Bienvenido a post-T!</h1>
	<br>
	<br>
	<h4>¿Cómo puedo registrarme?</h4>
	<p align='justify'> Para poder tener una cuenta con nosotros debe llegarte una invitación para poder acceder. </p>
</div>
<div class='col-md-4'>
	<%= image_tag '/pira01.png' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head lang='es-ES'>
<link rel="shortcut icon" href="/favicon.ico" />
<title> Post-T! </title>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag "bootstrap", media: "all", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body>
  <div class='nav navbar-default navbar-inner'>
    <%= render 'layouts/navbar' %>
  </div>
  <div class='container'>
    <div class='row'>
      <div class='col-md-2'>
        <% if current_user %>
          <%= render 'layouts/sidebar' %>
        <% else %>
          <br> <br> <br> <br> <br>
          <%= form_tag sessions_path do %>
            <% flash.each do |name, msg| %>
              <%= content_tag :div, msg, :id => "flash_#{msg}", class: 'alert alert-dismissable alert-danger'%>
            <% end %>
            <%= label_tag :nickname, 'Mote' %>
            <%= text_field_tag :nickname, '', class:'form-control' %>
            <%= label_tag :password, 'Contraseña' %>
            <%= password_field_tag :password, '', class:'form-control' %>
            <br>
            <button type='submit' class='btn btn-primary btn-sm' > Entrar </button>
          <% end %>
        <% end %>
      </div>
      <% if current_user %>
        <div class='col-md-10'>
          <%= yield %>
        </div>
      <% else %>
        <div class='col-md-12'> <%= render 'layouts/without_log_in' %> </div>
      <% end %>
    </div>
  </div>
</body>
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p align='center'> Post-T! - 2013 </p>
    </div>
  </div>
</footer>
</html>